credentials:
  usernames:
    creator:
      email: creator@example.com
      name: Creator
      password: '$2b$12$zFzvHhVNo1qY7aG4sK9gIuPCrXkqRoUmYbZ0ZnBhYm7wSTm09UI1q'  # 'Creator2025!'

cookie:
  name: my_cookie
  key: some_secret_key_123
  expiry_days: 30
